on:
  push:
    branches: [main, rc-v**]

name: deploy-tutorials

jobs:
  deploy-tutorials:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT:       ${{ secrets.GITHUB_TOKEN }}
      SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
      SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - uses: rstudio/shinycoreci/.github/actions/install-r-package@v1
        with:
          extra-packages: |
            remotes
            rsconnect
            glue

      - name: Install package from GitHub
        shell: Rscript {0}
        run:  |
          remotes::pkg_install("rstudio/sortable")

      - name: Deploy tutorials
        shell: Rscript {0}
        run: source("scripts/deploy_on_travis.R")
