# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  pull_request:
    branches: [main]

name: Routine package checks

jobs:
  routine:
    uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
